/**
 * Type exports for @johnqh/wildduck_client
 * Re-exporting WildDuck types from @johnqh/types for convenience
 */

export * from "@johnqh/types";

// Export only new types not present in @johnqh/types
export type {
  CreateUserResponse,
  UserResponse,
  UserListItem,
  UserListResponse,
  ResolveUserResponse,
  QuotaResetResponse,
  PasswordResetRequest,
  PasswordResetResponse,
  MailboxListItem,
  MailboxListResponse,
  CreateMailboxResponse,
  MailboxResponse,
  MessageListItem,
  MessageListResponse,
  MessageResponse,
  SearchMessagesRequest,
  SearchApplyRequest,
  SearchApplyResponse,
  UpdateMessageResponse,
  UploadMessageResponse,
  SubmitMessageResponse,
  AddressListItem,
  AddressListResponse,
  CreateAddressRequest,
  CreateAddressResponse,
  UpdateAddressRequest,
  ForwardedAddressListItem,
  ForwardedAddressListResponse,
  ResolveAddressResponse,
  FilterListItem,
  FilterListResponse,
  CreateFilterResponse,
  AutoreplyResponse,
  ASPListItem,
  ASPListResponse,
  CreateASPRequest,
  CreateASPResponse,
  ASPResponse,
  StorageUploadRequest,
  StorageUploadResponse,
  StorageListItem,
  StorageListResponse,
  SettingItem,
  SettingsListResponse,
  SettingResponse,
  UpdateSettingRequest,
  HealthResponse,
  WebhookListItem,
  WebhookListResponse,
  CreateWebhookRequest,
  CreateWebhookResponse,
  CreateAuditRequest,
  CreateAuditResponse,
  AuditResponse,
  DKIMListItem,
  DKIMListResponse,
  CreateDKIMRequest,
  CreateDKIMResponse,
  SuccessResponse,
  DeleteResponse,
  PaginationParams,
  SessionParams,
  Address,
  Attachment,
  ContentType,
  BimiInfo,
  Limits,
  KeyInfo,
} from "./wildduck-types";
